[mirror]
# The local Debian mirror server
mirror-01 ansible_host=X.X.X.X # <--- REPLACE WITH YOUR MIRROR IP

[uat]
# UAT servers for testing patches
uat-server-01 ansible_host=X.X.X.X # <--- REPLACE WITH YOUR UAT IP

[prod]
# Production servers
prod-server-01 ansible_host=X.X.X.X # <--- REPLACE WITH YOUR PROD IP

[all_managed:children]
uat
prod
