---
- name: Update apt-mirror (sync only)
  hosts: mirror
  become: yes
  gather_facts: no

  tasks:
    - name: Run apt-mirror sync
      command: /usr/bin/apt-mirror /etc/apt/mirror.list
      register: mirror_update
      changed_when: true

    - name: Show last lines of output
      debug:
        msg: "{{ (mirror_update.stdout_lines | default([]))[-25:] }}"
